import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/HomePage/Navbar/Navbar'
import AuthProvider from '@/Components/Utilities/AuthProvider/AuthProvider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Scholarly-Nexus',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        <Toaster/>
      </body>
    </html>
  )
}
